server:
  port: 8888

spring:
  application:
    name: rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #bug epe if not config ,It'll be fixed in 2.1.3 release of Spring AMQP
    listener:
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
  security:
    user:
      name: yugj
      password: yugj
      roles: sys